package com.elypia.commandler.doc.test;

import com.elypia.commandler.ModulesContext;
import com.elypia.commandler.doc.DocBuilder;
import com.elypia.commandler.doc.entities.*;
import com.elypia.commandler.doc.impl.*;
import org.junit.jupiter.api.*;

import java.io.IOException;
import java.util.List;

public class DocBuilderTest {

    private static ModulesContext context;
    private static DocBuilder builder;

    @BeforeAll
    public static void beforeAll() {
        context = new ModulesContext();
        context.addModules(
            MiscModule.class,
            OsuModule.class,
            RuneScapeModule.class,
            YouTubeModule.class
        );

        builder = new DocBuilder();
    }

    @Test
    public void testFromBuilder() throws IOException {
        String logo = "https://elypia.com/resources/logo_pic.png";

        AppData data = new AppData()
            .setName("TestApp")
            .setDescription("A static website generated by Commandler.")
            .setLogo(logo)
            .setFavicon(new Favicon("png", logo))
            .setStyle(new Style(
                ColorScheme.DARK_SCHEME,
                new FontFamily("Raleway", "https://fonts.googleapis.com/css?family=Raleway")
            ))
            .setSocial(List.of(
                new Social("fab fa-discord", "https://discord.gg/hprGMaM", "purple"),
                new Social( "fab fa-gitlab", "https://gitlab.com/Elypia", "orange"),
                new Social("fab fa-twitter", "https://twitter.com/Elypia", "blue")
            ));

        builder
            .setData(data)
            .setContext(context)
            .build();
    }

//    @Test
//    public void testFromConfig() throws IOException {
//        URL url = this.getClass().getResource("/testapp.toml");
//        AppData data = new AppData(url);
//
//        builder
//            .setData(data)
//            .setContext(context)
//            .build();
//    }
}
